// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCDLUsfYx8KYAa1ILou3MVvIWb0kBXkz0',
    appId: '1:763873682114:web:4e11ca011bc5432d1b515b',
    messagingSenderId: '763873682114',
    projectId: 'todo-52e05',
    authDomain: 'todo-52e05.firebaseapp.com',
    storageBucket: 'todo-52e05.appspot.com',
    measurementId: 'G-5HJWXYZFQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSHLkAGRhStEKVNfPVUDmJ75eLccz__Ro',
    appId: '1:763873682114:android:ca9462d1be4acf341b515b',
    messagingSenderId: '763873682114',
    projectId: 'todo-52e05',
    storageBucket: 'todo-52e05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIWPEz4zchYoiCPO6JJyBqsLrE04y9WvI',
    appId: '1:763873682114:ios:34ea7b35448d7d5f1b515b',
    messagingSenderId: '763873682114',
    projectId: 'todo-52e05',
    storageBucket: 'todo-52e05.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIWPEz4zchYoiCPO6JJyBqsLrE04y9WvI',
    appId: '1:763873682114:ios:34ea7b35448d7d5f1b515b',
    messagingSenderId: '763873682114',
    projectId: 'todo-52e05',
    storageBucket: 'todo-52e05.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCDLUsfYx8KYAa1ILou3MVvIWb0kBXkz0',
    appId: '1:763873682114:web:d82edfb857596c601b515b',
    messagingSenderId: '763873682114',
    projectId: 'todo-52e05',
    authDomain: 'todo-52e05.firebaseapp.com',
    storageBucket: 'todo-52e05.appspot.com',
    measurementId: 'G-R0G5QSQSMW',
  );
}
